<?xml version="1.0" encoding="ISO-8859-15"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>com.atosorigin.wfem</groupId>
	<artifactId>wfem-master-pom</artifactId>
	<version>4.0.3</version>
	<packaging>pom</packaging>
	<name>wfem-master-pom</name>
	<description>Pom principale di tutte le applicazioni Wfem</description>
	<properties>
		<bmed.ejb.version>3.0</bmed.ejb.version>
		<dep.BO.version>1.0.0</dep.BO.version>
		<dep.DAExperian.version>1.0.0</dep.DAExperian.version>
		<dep.javaee-api.version>7.0</dep.javaee-api.version>
		<dep.rdv-be-wfem-adeguatezzacedacri-ejbimpl.version>2.9.1</dep.rdv-be-wfem-adeguatezzacedacri-ejbimpl.version>
		<dep.rdv-be-wfem-framework-ejbimpl.version>22.0.0-RC-SNAPSHOT</dep.rdv-be-wfem-framework-ejbimpl.version>
		<dep.rdv-fe-wfem-itapdac-ejbimpl.version>9.0.0</dep.rdv-fe-wfem-itapdac-ejbimpl.version>
		<dep.rdv-fe-wfem-pdfwebforms-ejbimpl.version>9.0.0-RC-SNAPSHOT</dep.rdv-fe-wfem-pdfwebforms-ejbimpl.version>
		<dep.rdv-fe-wfem-pdfwebformsutil-ejbimpl.version>4.0.0</dep.rdv-fe-wfem-pdfwebformsutil-ejbimpl.version>
		<dep.rdv-fe-wfem-postcompletioncewutility-ejbimpl.version>6.0.0</dep.rdv-fe-wfem-postcompletioncewutility-ejbimpl.version>
		<dep.rdv-fe-wfem-wfemlayout-ejbimpl.version>9.0.1</dep.rdv-fe-wfem-wfemlayout-ejbimpl.version>
		<dep.rdv-lib-wfem-thirdparty-deps.version>3.0.0</dep.rdv-lib-wfem-thirdparty-deps.version>
		<dep.rdv-be-wfem-junitutil.version>1.2.0</dep.rdv-be-wfem-junitutil.version>
		<dep.servlet-api.version>2.5</dep.servlet-api.version>
		<dep.weblogic.wfem-thirdparty.implementation.version>1.0.0</dep.weblogic.wfem-thirdparty.implementation.version>
		<dep.weblogic.wfem-thirdparty.specification.version>1.0.0</dep.weblogic.wfem-thirdparty.specification.version>
		<dep.mockito-core.version>2.28.2</dep.mockito-core.version>
		<dep.powermock-api-mockito.version>2.0.0-RC.1</dep.powermock-api-mockito.version>
		<dep.powermock-module-junit4.version>2.0.0</dep.powermock-module-junit4.version>
		<dep.jacoco-maven-plugin.version>0.8.5</dep.jacoco-maven-plugin.version>
		<dep.jacoco-agent.version>0.8.5</dep.jacoco-agent.version>
		<m2e.jaxrs.activation>false</m2e.jaxrs.activation>
		<m2e.jpa.activation>false</m2e.jpa.activation>
		<m2e.jsf.activation>false</m2e.jsf.activation>
		<plugin.build-helper-maven-plugin.version>3.0.0</plugin.build-helper-maven-plugin.version>
		<plugin.lifecycle-mapping.version>1.0.0</plugin.lifecycle-mapping.version>
		<plugin.maven-compiler-plugin.version>3.3</plugin.maven-compiler-plugin.version>
		<plugin.maven-ear-plugin.version>2.10</plugin.maven-ear-plugin.version>
		<plugin.maven-eclipse-plugin.version>2.10</plugin.maven-eclipse-plugin.version>
		<plugin.maven-ejb-plugin.version>2.3</plugin.maven-ejb-plugin.version>
		<plugin.maven-war-plugin.version>3.3.2</plugin.maven-war-plugin.version>
		<plugin.maven.version>2.2</plugin.maven.version>
		<plugin.sortpom-maven-plugin.version>2.4.0</plugin.sortpom-maven-plugin.version>
		<plugin.weblogic-maven-plugin.adminurl>t3://localhost:7001</plugin.weblogic-maven-plugin.adminurl>
		<plugin.weblogic-maven-plugin.password>welcome1</plugin.weblogic-maven-plugin.password>
		<plugin.weblogic-maven-plugin.targets>AdminServer</plugin.weblogic-maven-plugin.targets>
		<plugin.weblogic-maven-plugin.user>weblogic</plugin.weblogic-maven-plugin.user>
		<plugin.weblogic-maven-plugin.version>10.3.6.0</plugin.weblogic-maven-plugin.version>
		<project.build.sourceEncoding>ISO-8859-15</project.build.sourceEncoding>
		<project.build.sourceJdk>1.8</project.build.sourceJdk>
		<project.build.targetEncoding>ISO-8859-15</project.build.targetEncoding>
		<project.build.targetJdk>1.8</project.build.targetJdk>
		<servlet-api.version>${dep.servlet-api.version}</servlet-api.version>
		<weblogic.ear-jar>${basedir}/target/${project.artifactId}.ear</weblogic.ear-jar>
		<weblogic.ear-name>${project.artifactId}</weblogic.ear-name>
		<weblogic.target-servers>AdminServer</weblogic.target-servers>
		<wls.version>10.3.5</wls.version>
		<workspace.dir>C:/DevRootOepe/ProjectsMaven</workspace.dir>
		<!-- properties abilitanti jacoco per code coverage -->
		<sonar.jacoco.reportPaths>${project.basedir}/target/jacoco.exec</sonar.jacoco.reportPaths>
		<sonar.core.codeCoveragePlugin>jacoco</sonar.core.codeCoveragePlugin>
		<sonar.exclusions>WebContent/**/*, test/**/*</sonar.exclusions>		
		<sonar.coverage.exclusions>WebContent/**/*, **/*Bean.java, **/*Model.java, **/*Entity.java, **/*Dto.java, **/*Type.java, **/*Enum.java, **/*Exception.java, **/*Constant*.java, **/*DataHelper.java, **/dummyejb/**/*, test/**/*</sonar.coverage.exclusions>		
	</properties>
	<dependencies>
		<dependency>
			<groupId>com.businessobjects.dsws</groupId>
			<artifactId>blws-consumer-jaxws</artifactId>
			<version>${dep.BO.version}</version>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>javax.servlet</groupId>
			<artifactId>servlet-api</artifactId>
			<version>${dep.servlet-api.version}</version>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>javax</groupId>
			<artifactId>javaee-api</artifactId>
			<version>${dep.javaee-api.version}</version>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>com.atosorigin.wfem</groupId>
			<artifactId>rdv-lib-wfem-thirdparty-deps</artifactId>
			<version>${dep.rdv-lib-wfem-thirdparty-deps.version}</version>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>org.mockito</groupId>
			<artifactId>mockito-core</artifactId>
			<version>${dep.mockito-core.version}</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.powermock</groupId>
			<artifactId>powermock-api-mockito2</artifactId>
			<version>${dep.powermock-api-mockito.version}</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.powermock</groupId>
			<artifactId>powermock-module-junit4</artifactId>
			<version>${dep.powermock-module-junit4.version}</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.jacoco</groupId>
			<artifactId>org.jacoco.agent</artifactId>
			<version>${dep.jacoco-agent.version}</version>
			<classifier>runtime</classifier>
		</dependency>
	</dependencies>
	<build>
		<directory>${project.basedir}/bin</directory>
		<!-- finalName>${project.artifactId}</finalName -->
		<finalName>${project.name}</finalName>
		<sourceDirectory>${project.basedir}/src</sourceDirectory>
		<outputDirectory>${project.build.directory}</outputDirectory>
		<testOutputDirectory>${project.basedir}/target/test-classes</testOutputDirectory>
		<resources>
			<resource>
				<directory>${project.basedir}/src</directory>
				<includes>
					<include>**/*</include>
				</includes>
				<excludes>
					<exclude>**/*.java</exclude>
				</excludes>
			</resource>
		</resources>
		<testResources>
			<testResource>
				<directory>${project.basedir}/test/resources</directory>
			</testResource>
		</testResources>
		<pluginManagement>
			<plugins>			
				<plugin>
					<groupId>org.jacoco</groupId>
					<artifactId>jacoco-maven-plugin</artifactId>
					<version>${dep.jacoco-maven-plugin.version}</version>
					<executions>
					    <execution>
							<id>default-prepare-agent</id>
							<goals>
							   <goal>prepare-agent</goal>
							</goals>
						</execution>
						<execution>
							<id>default-instrument</id>
							<goals>
								<goal>instrument</goal>
							</goals>
						</execution>
						<execution>
							<id>default-restore-instrumented-classes</id>
							<goals>
								<goal>restore-instrumented-classes</goal>
							</goals>
						</execution>
						<execution>
							<id>report</id>
							<phase>prepare-package</phase>
							<goals>
								<goal>report</goal>
							</goals>
							<configuration>
								<destfile>${project.basedir}/target/jacoco.exec</destfile>
								<datafile>${project.basedir}/target/jacoco.exec</datafile>
							</configuration>
						</execution>
					</executions>					
				</plugin>
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-surefire-plugin</artifactId>
					<version>3.0.0-M5</version>
					<configuration>
						<reportsDirectory>${project.basedir}/target/surefire-reports</reportsDirectory>
						<argLine>-Xmx2048m -Xms1024m -XX:MaxPermSize=512m</argLine>
						<systemPropertyVariables>
							<jacoco-agent.destfile>${project.basedir}/target/jacoco.exec</jacoco-agent.destfile>
						</systemPropertyVariables>						
					</configuration>
					<dependencies>
						<dependency>
							<groupId>org.apache.maven.surefire</groupId>
							<artifactId>surefire-junit47</artifactId>
							<version>3.0.0-M5</version>
						</dependency>
					</dependencies>
				</plugin>      
				<plugin>
					<groupId>com.oracle.weblogic</groupId>
					<artifactId>weblogic-maven-plugin</artifactId>
					<version>${plugin.weblogic-maven-plugin.version}</version>
					<configuration>
						<adminurl>${plugin.weblogic-maven-plugin.adminurl}</adminurl>
						<user>${plugin.weblogic-maven-plugin.user}</user>
						<password>${plugin.weblogic-maven-plugin.password}</password>
						<targets>${plugin.weblogic-maven-plugin.targets}</targets>
						<source>${project.build.directory}/${project.build.finalName}.${project.packaging}</source>
						<name>${project.build.finalName}</name>
						<action>deploy</action>
						<verbose>true</verbose>
					</configuration>
					<executions>
						<execution>
							<goals>
								<goal>deploy</goal>
							</goals>
							<phase>install</phase>
						</execution>
					</executions>
				</plugin>
				<plugin>
					<groupId>com.github.ekryd.sortpom</groupId>
					<artifactId>sortpom-maven-plugin</artifactId>
					<version>${plugin.sortpom-maven-plugin.version}</version>
					<configuration>
						<predefinedSortOrder>custom_1</predefinedSortOrder>
						<lineSeparator>\n</lineSeparator>
						<encoding>${project.build.sourceEncoding}</encoding>
						<sortProperties>true</sortProperties>
						<keepBlankLines>true</keepBlankLines>
						<sortDependencies>scope</sortDependencies>
					</configuration>
					<executions>
						<execution>
							<goals>
								<goal>sort</goal>
							</goals>
							<phase>compile</phase>
						</execution>
					</executions>
				</plugin>
				<plugin>
					<groupId>org.eclipse.m2e</groupId>
					<artifactId>lifecycle-mapping</artifactId>
					<version>${plugin.lifecycle-mapping.version}</version>
					<configuration>
						<lifecycleMappingMetadata>
							<pluginExecutions>
								<pluginExecution>
									<pluginExecutionFilter>
										<groupId>com.github.ekryd.sortpom</groupId>
										<artifactId>sortpom-maven-plugin</artifactId>
										<versionRange>[2.4.0,)</versionRange>
										<goals>
											<goal>sort</goal>
										</goals>
									</pluginExecutionFilter>
									<action>
										<ignore></ignore>
									</action>
								</pluginExecution>
							</pluginExecutions>
						</lifecycleMappingMetadata>
					</configuration>
				</plugin>
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-war-plugin</artifactId>
					<version>${plugin.maven-war-plugin.version}</version>
					<configuration>
						<warSourceDirectory>WebContent</warSourceDirectory>
						<failOnMissingWebXml>false</failOnMissingWebXml>
					</configuration>
				</plugin>
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-ear-plugin</artifactId>
					<version>${plugin.maven-ear-plugin.version}</version>
					<configuration>
						<filtering>true</filtering>
						<version>5</version>
						<defaultLibBundleDir></defaultLibBundleDir>
						<displayName>${project.parent.name}</displayName>
						<archive>
							<addMavenDescriptor>true</addMavenDescriptor>
							<manifest>
								<addDefaultImplementationEntries>false</addDefaultImplementationEntries>
								<addDefaultSpecificationEntries>false</addDefaultSpecificationEntries>
							</manifest>
							<manifestEntries>
								<Created-On>${build.timestamp}</Created-On>
								<extension-name>${project.parent.name}</extension-name>
								<specification-title>${project.parent.name}-${project.version}</specification-title>
								<specification-version>${parsedVersion.majorVersion}.${parsedVersion.minorVersion}.${parsedVersion.incrementalVersion}</specification-version>
								<implementation-version>${parsedVersion.majorVersion}.${parsedVersion.minorVersion}.${parsedVersion.incrementalVersion}</implementation-version>
								<implementation-vendor>Engineering</implementation-vendor>
							</manifestEntries>
						</archive>
					</configuration>
				</plugin>
				<plugin>
					<groupId>org.codehaus.mojo</groupId>
					<artifactId>build-helper-maven-plugin</artifactId>
					<version>${plugin.build-helper-maven-plugin.version}</version>
					<executions>
						<execution>
							<id>parse-version</id>
							<goals>
								<goal>parse-version</goal>
							</goals>
							<phase>validate</phase>
						</execution>
					</executions>
				</plugin>
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-compiler-plugin</artifactId>
					<version>${plugin.maven-compiler-plugin.version}</version>
					<configuration>
						<source>${project.build.sourceJdk}</source>
						<target>${project.build.targetJdk}</target>
						<encoding>${project.build.sourceEncoding}</encoding>
						<compilerArgs>
							<arg>-Xlint:unchecked</arg>
						</compilerArgs>
					</configuration>
				</plugin>
				<plugin>
					<artifactId>maven-antrun-plugin</artifactId>
					<version>1.8</version>
					<executions>
						<execution>
							<id>prepare-package</id>
							<goals>
								<goal>run</goal>
							</goals>
							<phase>prepare-package</phase>
							<configuration>
								<target>
									<replace dir="${project.build.directory}/prgm/moduleVersion"
										token="@@VERSION@@" value="${project.parent.version}">
										<include name="**/*.version"></include>
									</replace>																																
								</target>								
							</configuration>
						</execution>						
						<execution>
							<id>post-integration-test</id>
							<goals>
								<goal>run</goal>
							</goals>
							<phase>post-integration-test</phase>
							<configuration>
								<target>																		
									<delete includeEmptyDirs="true" failonerror="false">
									  <fileset dir="${project.build.directory}/generated-classes/jacoco" includes="**/*" />
									</delete>																	
								</target>								
							</configuration>
						</execution>												
					</executions>
				</plugin>				
				<plugin>
					<groupId>org.codehaus.mojo</groupId>
					<artifactId>truezip-maven-plugin</artifactId>
					<version>1.2</version>
					<executions>
						<execution>
							<id>remove-a-file-in-sub-archive</id>
							<goals>
								<goal>remove</goal>
							</goals>
							<phase>post-integration-test</phase>
							<configuration>
								<verbose>false</verbose>
								<fileset>
									<directory>${project.build.directory}/${project.name}.jar/</directory>
									<includes>
										<include>generated-classes/jacoco/**/*</include>
									</includes>
								</fileset>
							</configuration>
						</execution>
					</executions>
				</plugin>        
			</plugins>
		</pluginManagement>
		<plugins>
			<plugin>
				<groupId>org.codehaus.mojo</groupId>
				<artifactId>build-helper-maven-plugin</artifactId>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-ejb-plugin</artifactId>
				<version>${plugin.maven-ejb-plugin.version}</version>
				<configuration>
					<ejbVersion>${bmed.ejb.version}</ejbVersion>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-eclipse-plugin</artifactId>
				<version>${plugin.maven-eclipse-plugin.version}</version>
			</plugin>			
		</plugins>
	</build>
</project>
