<?xml version="1.0" encoding="utf-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>prgm.pdfwebformsdrivers.personalpirvariazionepianopac</groupId>
		<artifactId>rdv-fe-wfem-pdfwebformsdrivers-personalpirvariazionepianopac</artifactId>
		<version>5.0.0</version>
	</parent>
	<artifactId>rdv-fe-wfem-pdfwebformsdrivers-personalpirvariazionepianopac-ejbimpl</artifactId>
	<name>PdfWebFormsDrivers-PersonalPirVariazionePianoPac</name>
	<packaging>ejb</packaging>
	<properties>
		<sonar.tests>${project.basedir}/test</sonar.tests>
		<sonar.sources>${project.basedir}/ver00001</sonar.sources>
	</properties>
	<dependencies>
		<dependency>
			<groupId>prgm.pdfwebformsutil.drivers</groupId>
			<artifactId>rdv-fe-wfem-pdfwebformsutil-ejbimpl</artifactId>
			<version>5.1.0</version>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>prgm.pdfwebforms.backend</groupId>
			<artifactId>rdv-fe-wfem-pdfwebforms-ejbimpl</artifactId>
			<version>9.0.0-RC-SNAPSHOT</version>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>com.atosorigin.wfem</groupId>
			<artifactId>rdv-be-wfem-framework-ejbimpl</artifactId>
			<version>${dep.rdv-be-wfem-framework-ejbimpl.version}</version>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>prgm.pdfwebformsdrivers.postcompletioncewutility</groupId>
			<artifactId>rdv-fe-wfem-pdfwebformsdrivers-postcompletioncewutility-ejbimpl</artifactId>
			<version>${dep.rdv-fe-wfem-postcompletioncewutility-ejbimpl.version}</version>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>prgm.pdfwebformspolizzeutil</groupId>
			<artifactId>rdv-fe-wfem-pdfwebformspolizzeutil-ejbimpl</artifactId>
			<version>6.4.0</version>
			<scope>provided</scope>
		</dependency>
	</dependencies>
	<build>
		<resources>
			<resource>
				<directory>${project.basedir}/src</directory>
				<excludes>
					<exclude>**/*.java</exclude>
				</excludes>
				<includes>
					<include>**/*</include>
				</includes>
			</resource>
			<resource>
				<directory>${project.basedir}/ver00001</directory>
				<excludes>
					<exclude>**/*.java</exclude>
				</excludes>
				<includes>
					<include>**/*</include>
				</includes>
			</resource>
		</resources>
		<plugins>
			<plugin>
				<groupId>org.codehaus.mojo</groupId>
				<artifactId>build-helper-maven-plugin</artifactId>
				<executions>
					<execution>
						<phase>generate-sources</phase>
						<goals>
							<goal>add-source</goal>
						</goals>
						<configuration>
							<sources>
								<source>${project.basedir}/src</source>
								<source>${project.basedir}/ver00001</source>
							</sources>
						</configuration>
					</execution>
					<execution>
						<id>add-test-source</id>
						<phase>generate-test-sources</phase>
						<goals>
							<goal>add-test-source</goal>
						</goals>
						<configuration>
							<sources>
								<source>${project.basedir}/test</source>
							</sources>
						</configuration>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<artifactId>maven-antrun-plugin</artifactId>
			</plugin>
			<plugin>
				<groupId>org.jacoco</groupId>
				<artifactId>jacoco-maven-plugin</artifactId>
			</plugin>
			<plugin>
				<groupId>org.codehaus.mojo</groupId>
				<artifactId>truezip-maven-plugin</artifactId>
			</plugin>
		</plugins>
	</build>
</project>
