insert into SER_MIFID.ADEG_SRV_ANAG_CHIAMANTI (	COD_SISTEMA_CHIAMANTE,	DESCRIZIONE,		FLAG_ADEGUATEZZA,	FLAG_USO_PROFILO_PROVV,	FLAG_CONTROLLO_PER_FREQUENZA,	FLAG_TRACCIA_ESITO) 
values (										'PDFPREVIEW',			'Pdf compilabili',	'S',				'S',					'S',							'N');
insert into SER_MIFID.ADEG_SRV_ANAG_CHIAMANTI (	COD_SISTEMA_CHIAMANTE,	DESCRIZIONE,		FLAG_ADEGUATEZZA,	FLAG_USO_PROFILO_PROVV,	FLAG_CONTROLLO_PER_FREQUENZA,	FLAG_TRACCIA_ESITO) 
values (										'PDFPREVIEW',			'Pdf compilabili',	'N',				'S',					'S',							'N');

insert into SER_MIFID.ADEG_SRV_ANAG_CHIAMANTI (	COD_SISTEMA_CHIAMANTE,	DESCRIZIONE,		FLAG_ADEGUATEZZA,	FLAG_USO_PROFILO_PROVV,	FLAG_CONTROLLO_PER_FREQUENZA,	FLAG_TRACCIA_ESITO) 
values (									  	'PDFSEND',				'Pdf compilabili',	'S',				'S',					'S',							'S');
insert into SER_MIFID.ADEG_SRV_ANAG_CHIAMANTI (	COD_SISTEMA_CHIAMANTE,	DESCRIZIONE,		FLAG_ADEGUATEZZA,	FLAG_USO_PROFILO_PROVV,	FLAG_CONTROLLO_PER_FREQUENZA,	FLAG_TRACCIA_ESITO) 
values (									  	'PDFSEND',				'Pdf compilabili',	'N',				'S',					'S',							'S');

insert into SER_MIFID.ADEG_SRV_ANAG_CHIAMANTI (	COD_SISTEMA_CHIAMANTE,	DESCRIZIONE,		FLAG_ADEGUATEZZA,	FLAG_USO_PROFILO_PROVV,	FLAG_CONTROLLO_PER_FREQUENZA,	FLAG_TRACCIA_ESITO) 
values (									  	'PDFSIGN',				'Pdf compilabili',	'S',				'N',					'S',							'S');
insert into SER_MIFID.ADEG_SRV_ANAG_CHIAMANTI (	COD_SISTEMA_CHIAMANTE,	DESCRIZIONE,		FLAG_ADEGUATEZZA,	FLAG_USO_PROFILO_PROVV,	FLAG_CONTROLLO_PER_FREQUENZA,	FLAG_TRACCIA_ESITO) 
values (									  	'PDFSIGN',				'Pdf compilabili',	'N',				'N',					'N',							'S');

commit;
