use CEPE
go

-- PRIT
-- aggiornamento pdf (CALL_SRV_DISPOSITIVA_BMED in origine era NULL)
update PDF_ANAG set COD_PRODOTTO_PRIT=28601, COD_OPERAZIONE_PRIT=28601, CALL_SRV_DISPOSITIVA_BMED='S' where MOM_CODE='BAN9'
-- invalido vecchio legame
update CEPE_PT_RETEP_PRODOPER set PT_PRODOPER_F_VALIDITA='N' where PT_PRODOTTO_N_PT_PRODOTTO=162 AND PT_OPERAZIONE_N_PT_OPERAZIONE=810
-- attivo nuovo prodotto
update CEPE_PT_RETEP_PRODOTTO set PT_PRODOTTO_F_VALIDITA='S' where PT_PRODOTTO_N_PT_PRODOTTO=28601
go

-- Attivazione processo target: verrà fatta successivamente con RFC dedicata
UPDATE PDF_CONFIG SET ATTIVO = 'N' WHERE SEZIONE = 'AML' AND PARAMETRO = 'MODULI_CON_QUESTIONARIO_AML_AN43'
UPDATE PDF_CONFIG SET ATTIVO = 'N' WHERE SEZIONE = 'AML' AND PARAMETRO = 'MODULI_CON_QUESTIONARIO_AML_AN44'
UPDATE PDF_CONFIG SET ATTIVO = 'S' WHERE SEZIONE = 'AML' AND PARAMETRO = 'MODULI_CON_QUESTIONARIO_AML_BAN9'
UPDATE PDF_CONFIG SET VALORE = 'N', ATTIVO = 'N' WHERE SEZIONE = 'AML' AND PARAMETRO = 'PROCESSO_TATTICO'
go

PRINT "AML target attivato"
go


