use CEPE
go

-- pulizia nuovo legame
delete from CEPE_PT_RETEP_PRODOPER where PT_PRODOTTO_N_PT_PRODOTTO=28601 and PT_OPERAZIONE_N_PT_OPERAZIONE=28601
go
-- inserimento nuovo codice prodotto inizialmente non valido (processo tattico)
IF NOT EXISTS (SELECT * FROM CEPE_PT_RETEP_PRODOTTO WHERE PT_PRODOTTO_N_PT_PRODOTTO = 28601)
BEGIN
	INSERT INTO CEPE_PT_RETEP_PRODOTTO (PT_PRODOTTO_N_PT_PRODOTTO, PT_PRODOTTO_X_PT_PRODOTTO, PT_PRODOTTO_F_VALIDITA, PT_PRODOTTO_D_VARIAZIONE)
	VALUES (28601, 'Adeguata Verifica', 'N', getdate())
END
go
-- inserimento nuovo codice operazione
IF NOT EXISTS (SELECT * FROM CEPE_PT_RETEP_OPERAZIONE WHERE PT_OPERAZIONE_N_PT_OPERAZIONE = 28601)
BEGIN
	INSERT INTO CEPE_PT_RETEP_OPERAZIONE (PT_OPERAZIONE_N_PT_OPERAZIONE, PT_OPERAZIONE_X_PT_OPERAZIONE, PT_OPERAZIONE_F_VALIDITA, PT_OPERAZIONE_D_VARIAZIONE)
	VALUES (28601, 'Operazione di investimento', 'S', getdate())
END
go
-- inserimento nuovo legame (vecchio legame: prodotto 162, operazine 810)
INSERT INTO CEPE_PT_RETEP_PRODOPER (PT_PRODOTTO_N_PT_PRODOTTO, PT_OPERAZIONE_N_PT_OPERAZIONE, PT_LINEA_N_LINEA, PT_PRODOPER_F_VALIDITA, PT_PRODOPER_F_CONTROLLOFIRME, PT_PRODOPER_D_VARIAZIONE)
VALUES (28601, 28601, 0, 'S', 'N', getdate())
go

PRINT "Prodotti/Operazioni PRIT per BAN9 configurati"

