package prgm.pdfwebformsutil.drivers;

public enum PdfEventEnum {
	NONE,
	INIT_PDF,
	LOAD_PDF,
	SUBMIT_PDF,
	VERIFY_PDF,
	VERIFY_COPERNICO_PDF,
	PDF_VERIFIED,	
	PDF_PREVIEW,
	COMPILATION_MODE_SELECTION,
	PDF_COMPLETED,
	PROVIDE_PRIT_DATA,
	PROVIDE_MIFID_DATA,
	PROVIDE_REPORT_ADEGUATEZZA,
	PROVIDE_COMPILATION_MODES,
	PAGE_ONLOAD,
	PAGE_ONCHANGE;	
}
