use CEPE
go

UPDATE PDF_INSTANCE SET CREATION_USERTYPE='SEDE' WHERE CREATION_USERTYPE IS NULL and isnumeric(CREATION_USER)=0
GO

UPDATE PDF_INSTANCE SET CREATION_USERTYPE='RETE' WHERE CREATION_USERTYPE IS NULL and isnumeric(CREATION_USER)=1
GO

PRINT "column CREATION_USERTYPE updated"
