<?xml version="1.0" encoding="ISO-8859-15"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>prgm.moke.menupum</groupId>
    <artifactId>rdv-fe-wfem-mokemenu</artifactId>
    <version>5.0.0-RC-SNAPSHOT</version>
  </parent>
  <artifactId>rdv-fe-wfem-mokemenu-ejbimpl</artifactId>
  <name>MokeMenu</name>
  <properties>
    <sonar.tests>${project.basedir}/test</sonar.tests>
    <sonar.sources>${project.basedir}/src</sonar.sources>
  </properties>
  <dependencies>
    <dependency>
      <groupId>com.atosorigin.wfem</groupId>
      <artifactId>rdv-be-wfem-framework-ejbimpl</artifactId>
      <version>${dep.rdv-be-wfem-framework-ejbimpl.version}</version>
      <scope>provided</scope>
    </dependency>
    <dependency>
		<groupId>junit</groupId>
		<artifactId>junit</artifactId>
		<version>4.13.2</version>
		<scope>test</scope>
	</dependency>
	<dependency>
		<groupId>org.mockito</groupId>
		<artifactId>mockito-core</artifactId>
		<version>4.11.0</version>
		<scope>test</scope>
	</dependency>
	<dependency>
		<groupId>org.mockito</groupId>
		<artifactId>mockito-inline</artifactId>
		<version>4.11.0</version>
		<scope>test</scope>
	</dependency> 
  </dependencies>
  <build>
    <resources>
      <resource>
        <directory>${project.basedir}/src</directory>
        <includes>
          <include>**/*</include>
        </includes>
        <excludes>
          <exclude>**/*.java</exclude>
        </excludes>
      </resource>
    </resources>
    <plugins>
      <plugin>
        <groupId>org.codehaus.mojo</groupId>
        <artifactId>build-helper-maven-plugin</artifactId>
        <executions>
          <execution>
            <goals>
              <goal>add-source</goal>
            </goals>
            <phase>generate-sources</phase>
            <configuration>
              <sources>
                <source>${project.basedir}/src</source>
              </sources>
            </configuration>
          </execution>
			<execution>
				<id>add-test-source</id>
				<phase>generate-test-sources</phase>
				<goals>
					<goal>add-test-source</goal>
				</goals>
				<configuration>
					<sources>
						<source>${project.basedir}/test</source>
					</sources>
				</configuration>
			</execution>
        </executions>
      </plugin>
      <plugin>
        <artifactId>maven-antrun-plugin</artifactId>
        <executions>
          <execution>
            <phase>prepare-package</phase>
          </execution>
        </executions>
      </plugin>
	  <plugin>
		<groupId>org.jacoco</groupId>
		<artifactId>jacoco-maven-plugin</artifactId>
	  </plugin>
	  <plugin>
		<groupId>org.codehaus.mojo</groupId>
		<artifactId>truezip-maven-plugin</artifactId>
	   </plugin>
    </plugins>
  </build>
  <profiles>
    <profile>
      <id>copyjar</id>
      <build>
        <plugins>
          <plugin>
            <artifactId>maven-antrun-plugin</artifactId>
          </plugin>
        </plugins>
      </build>
    </profile>
  </profiles>
</project>
