UPDATE SOGG_POSIZINFORM.DOM_STATO_CONTR
SET FLG_STATO_BLOC = 'S'
, GSTD_M_NOM_ULT_MODF = 'RM59806'
, GSTD_X_USER = 'MOVING'
, GSTD_D_ULT_MODF_RECORD = sysdate
, GSTD_X_TIP_MODF = 'M'
WHERE COD_STATO_CONTR = '003' AND COD_TIPO_PROD_CONTR = 'CC';

UPDATE SOGG_POSIZINFORM.DOM_STATO_CONTR
SET  FLG_STATO_BLOC = 'S'
, GSTD_M_NOM_ULT_MODF = 'RM59806'
, GSTD_X_USER = 'MOVING'
, GSTD_D_ULT_MODF_RECORD = sysdate
, GSTD_X_TIP_MODF = 'M'
WHERE COD_STATO_CONTR = '004' AND COD_TIPO_PROD_CONTR = 'CC';

UPDATE SOGG_POSIZINFORM.DOM_STATO_CONTR
SET FLG_STATO_BLOC = 'S'
, GSTD_M_NOM_ULT_MODF = 'RM59806'
, GSTD_X_USER = 'MOVING'
, GSTD_D_ULT_MODF_RECORD = sysdate
, GSTD_X_TIP_MODF = 'M'
WHERE COD_STATO_CONTR = '005' AND COD_TIPO_PROD_CONTR = 'CC';

UPDATE SOGG_POSIZINFORM.DOM_STATO_CONTR
SET FLG_STATO_BLOC = 'S'
, GSTD_M_NOM_ULT_MODF = 'RM59806'
, GSTD_X_USER = 'MOVING'
, GSTD_D_ULT_MODF_RECORD = sysdate
, GSTD_X_TIP_MODF = 'M'
WHERE COD_STATO_CONTR = '006' AND COD_TIPO_PROD_CONTR = 'CC';

commit;