<%@ page import="prgm.ita.anagraficaclienti.facade.Costanti"%>
<%@ page contentType="application/javascript; charset=UTF-8" %>

var Costanti_VALORE_FLAG_STATO_CONFERMATO="<%=Costanti.VALORE_FLAG_STATO_CONFERMATO%>";
var Costanti_COD_NAZIONE_ITALIA="<%=Costanti.COD_NAZIONE_ITALIA%>";
var Costanti_COD_UIC_NAZIONE_ITALIA="<%=Costanti.COD_UIC_NAZIONE_ITALIA%>";
var Costanti_TIPO_DOCUMENTO_PATENTE="<%=Costanti.TIPO_DOCUMENTO_PATENTE%>";
var Costanti_TIPO_DOCUMENTO_CARTA_IDENTITA_ESTERA="<%=Costanti.TIPO_DOCUMENTO_CARTA_IDENTITA_ESTERA%>";
var Costanti_TIPO_DOCUMENTO_PASSAPORTO_ESTERO="<%=Costanti.TIPO_DOCUMENTO_PASSAPORTO_ESTERO%>";
var Costanti_TIPO_DOCUMENTO_CARTA_IDENTITA="<%=Costanti.TIPO_DOCUMENTO_CARTA_IDENTITA%>";
var Costanti_CODICE_SOTTOGRUPPO_ATTIVITA_CONSUMATORI="<%=Costanti.CODICE_SOTTOGRUPPO_ATTIVITA_CONSUMATORI%>";
var Costanti_CODICE_SOTTOGRUPPO_FAMIGLIE_CONSUMATRICI_PAESI_UE="<%=Costanti.CODICE_SOTTOGRUPPO_FAMIGLIE_CONSUMATRICI_PAESI_UE%>";
var Costanti_CODICE_SOTTOGRUPPO_FAMIGLIE_CONSUMATRICI_MEMBRI_U="<%=Costanti.CODICE_SOTTOGRUPPO_FAMIGLIE_CONSUMATRICI_MEMBRI_U%>";
var Costanti_CODICE_SOTTOGRUPPO_FAMIGLIE_CONSUMATRICI_PAESI_NO="<%=Costanti.CODICE_SOTTOGRUPPO_FAMIGLIE_CONSUMATRICI_PAESI_NO%>";
var Costanti_CODICE_ORIGINE_GLOBAL_SPECIALIST="<%=Costanti.CODICE_ORIGINE_GLOBAL_SPECIALIST%>";
var Costanti_CODICE_ORIGINE_LINEABLU="<%=Costanti.CODICE_ORIGINE_LINEABLU%>";
var Costanti_CODICE_ORIGINE_MEMBER_GET_MEMBER="<%=Costanti.CODICE_ORIGINE_MEMBER_GET_MEMBER%>";
var Costanti_CODICE_ORIGINE_MFORYOU="<%=Costanti.CODICE_ORIGINE_MFORYOU%>";
var Costanti_CODICE_ORIGINE_IMF="<%=Costanti.CODICE_ORIGINE_IMF%>";
var Costanti_STATO_CIVILE_CELIBE="<%=Costanti.STATO_CIVILE_CELIBE%>";
var Costanti_STATO_CIVILE_VEDOVO="<%=Costanti.STATO_CIVILE_VEDOVO%>";
var Costanti_CODICE_PROFESSIONE_STUDENTE="<%=Costanti.CODICE_PROFESSIONE_STUDENTE%>";
var Costanti_CODICE_PROFESSIONE_DISOCCUPATO="<%=Costanti.CODICE_PROFESSIONE_DISOCCUPATO%>";
var Costanti_CODICE_PROFESSIONE_DIPENDENTE_DIRIGENTE="<%=Costanti.CODICE_PROFESSIONE_DIPENDENTE_DIRIGENTE%>";
var Costanti_CODICE_PROFESSIONE_AUTONOMO_IMPRENDITORE="<%=Costanti.CODICE_PROFESSIONE_AUTONOMO_IMPRENDITORE%>";
var Costanti_CODICE_PROFESSIONE_SOGGETTO_APICALE="<%=Costanti.CODICE_PROFESSIONE_SOGGETTO_APICALE%>";
var Costanti_CODICE_CARICA_PUBBLICA_RICOPERTA_POLITICO_ISTITUZIONALE="<%=Costanti.CODICE_CARICA_PUBBLICA_RICOPERTA_POLITICO_ISTITUZIONALE%>";