USE CEPE
go

DELETE FROM PDF_CONFIG
WHERE SEZIONE = 'MIFID' AND PARAMETRO = 'CONTROLLO_CONCENTRAZIONE_FIA_PERCENTUALI_FAMIGLIE'

INSERT INTO PDF_CONFIG (SEZIONE, PARAMETRO, VALORE, ATTIVO, DESCRIZIONE)
VALUES ('MIFID', 'CONTROLLO_CONCENTRAZIONE_FIA_PERCENTUALI_FAMIGLIE', 'UCI=10', 'S', 'Percentuali famiglie controllo concentrazione fondi FIA')
GO

PRINT 'Configurazione percentuali fondi FIA effetuata'
go


