use CEPE
go

DELETE FROM PDF_CONFIG WHERE SEZIONE = 'PROCESS_DRIVER_REFERENCE' AND PARAMETRO = 'HOSTAPPLCALLBACK'
go

INSERT INTO PDF_CONFIG (SEZIONE, PARAMETRO, VALORE, ATTIVO, DESCRIZIONE, VALORE_ESTESO)
VALUES ('PROCESS_DRIVER_REFERENCE', 'HOSTAPPLCALLBACK', 'hostapplcallback.ver00001', 'S', 'Referenza al driver di processo HostApplCallback', NULL)
go

PRINT "configurazione aggiornata"
go

