use CEPE
go

insert into PDF_MODALITA_SOTTOSCRIZIONE (MODALITA_DI_SOTTOSCRIZIONE, X_MODALITA_DI_SOTTOSCRIZIONE) values ('COPERNICO','Copernico')
go

PRINT "copernico addeded to PDF_MODALITA_SOTTOSCRIZIONE"
