<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>com.atosorigin.wfem</groupId>
    <artifactId>wfem-master-pom</artifactId>
    <version>4.0.3</version>
  </parent>
  <groupId>com.atosorigin.wfem</groupId>
  <artifactId>rdv-fe-wfem-wfemlayout</artifactId>
  <version>9.0.1</version>
  <packaging>pom</packaging>
  <name>rdv-fe-wfem-wfemlayout</name>
  <modules>
    <module>rdv-fe-wfem-wfemlayout-ejbimpl</module>
    <module>rdv-fe-wfem-wfemlayout-web</module>
    <module>rdv-fe-wfem-wfemlayout-ear</module>
  </modules>
</project>
