<?xml version="1.0" encoding="ISO-8859-15"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>prgm.pdfwebforms.backend</groupId>
    <artifactId>rdv-fe-wfem-pdfwebforms</artifactId>
    <version>9.0.0-RC-SNAPSHOT</version>
  </parent>
  <artifactId>rdv-fe-wfem-pdfwebforms-ejbimpl</artifactId>
  <name>PdfWebForms</name>
  <properties>
    <sonar.tests>${project.basedir}/test</sonar.tests>
    <sonar.sources>${project.basedir}/src,${project.basedir}/sendprocess,${project.basedir}/signprocess,${project.basedir}/copernicoprocess,${project.basedir}/sostituzioni,${project.basedir}/mom,${project.basedir}/dataloader,${project.basedir}/publisher,${project.basedir}/messagecodesupdater</sonar.sources>
  </properties>
  <dependencies>
    <dependency>
      <groupId>com.atosorigin.wfem</groupId>
      <artifactId>rdv-be-wfem-framework-ejbimpl</artifactId>
      <version>22.0.0-RC-SNAPSHOT</version>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>prgm.itap.dac</groupId>
      <artifactId>rdv-fe-wfem-itapdac-ejbimpl</artifactId>
      <version>${dep.rdv-fe-wfem-itapdac-ejbimpl.version}</version>
      <scope>provided</scope>
    </dependency>
  </dependencies>
  <build>
    <resources>
      <resource>
        <directory>${project.basedir}/src</directory>
        <includes>
          <include>**/*</include>
        </includes>
        <excludes>
          <exclude>**/*.java</exclude>
        </excludes>
      </resource>
      <resource>
        <directory>${project.basedir}/agevolazioni</directory>
        <includes>
          <include>**/*</include>
        </includes>
        <excludes>
          <exclude>**/*.java</exclude>
        </excludes>
      </resource>
      <resource>
        <directory>${project.basedir}/mom</directory>
        <includes>
          <include>**/*</include>
        </includes>
        <excludes>
          <exclude>**/*.java</exclude>
        </excludes>
      </resource>
      <resource>
        <directory>${project.basedir}/carrello</directory>
        <includes>
          <include>**/*</include>
        </includes>
        <excludes>
          <exclude>**/*.java</exclude>
        </excludes>
      </resource>
      <resource>
        <directory>${project.basedir}/reportadeguatezza</directory>
        <includes>
          <include>**/*</include>
        </includes>
        <excludes>
          <exclude>**/*.java</exclude>
        </excludes>
      </resource>
      <resource>
        <directory>${project.basedir}/jsonsrv</directory>
        <includes>
          <include>**/*</include>
        </includes>
        <excludes>
          <exclude>**/*.java</exclude>
        </excludes>
      </resource>
      <resource>
        <directory>${project.basedir}/mifid</directory>
        <includes>
          <include>**/*</include>
        </includes>
        <excludes>
          <exclude>**/*.java</exclude>
        </excludes>
      </resource>
      <resource>
        <directory>${project.basedir}/copernicoprocess</directory>
        <includes>
          <include>**/*</include>
        </includes>
        <excludes>
          <exclude>**/*.java</exclude>
        </excludes>
      </resource>
      <resource>
        <directory>${project.basedir}/dataentryutil</directory>
        <includes>
          <include>**/*</include>
        </includes>
        <excludes>
          <exclude>**/*.java</exclude>
        </excludes>
      </resource>
      <resource>
        <directory>${project.basedir}/catalog</directory>
        <includes>
          <include>**/*</include>
        </includes>
        <excludes>
          <exclude>**/*.java</exclude>
        </excludes>
      </resource>
      <resource>
        <directory>${project.basedir}/sendprocess</directory>
        <includes>
          <include>**/*</include>
        </includes>
        <excludes>
          <exclude>**/*.java</exclude>
        </excludes>
      </resource>
      <resource>
        <directory>${project.basedir}/signprocess</directory>
        <includes>
          <include>**/*</include>
        </includes>
        <excludes>
          <exclude>**/*.java</exclude>
        </excludes>
      </resource>
      <resource>
        <directory>${project.basedir}/dataloader</directory>
        <includes>
          <include>**/*</include>
        </includes>
        <excludes>
          <exclude>**/*.java</exclude>
        </excludes>
      </resource>
      <resource>
        <directory>${project.basedir}/publisher</directory>
        <includes>
          <include>**/*</include>
        </includes>
        <excludes>
          <exclude>**/*.java</exclude>
        </excludes>
      </resource>
      <resource>
        <directory>${project.basedir}/idd</directory>
        <includes>
          <include>**/*</include>
        </includes>
        <excludes>
          <exclude>**/*.java</exclude>
        </excludes>
      </resource>
      <resource>
        <directory>${project.basedir}/sostituzioni</directory>
        <includes>
          <include>**/*</include>
        </includes>
        <excludes>
          <exclude>**/*.java</exclude>
        </excludes>
      </resource>
      <resource>
        <directory>${project.basedir}/messagecodesupdater</directory>
        <includes>
          <include>**/*</include>
        </includes>
        <excludes>
          <exclude>**/*.java</exclude>
        </excludes>
      </resource>
      <resource>
        <directory>${project.basedir}/aml</directory>
        <includes>
          <include>**/*</include>
        </includes>
        <excludes>
          <exclude>**/*.java</exclude>
        </excludes>
      </resource>
    </resources>
    <plugins>
      <plugin>
        <groupId>org.codehaus.mojo</groupId>
        <artifactId>build-helper-maven-plugin</artifactId>
        <executions>
          <execution>
            <goals>
              <goal>add-source</goal>
            </goals>
            <phase>generate-sources</phase>
            <configuration>
              <sources>
                <source>${project.basedir}/src</source>
                <source>${project.basedir}/agevolazioni</source>
                <source>${project.basedir}/mom</source>
                <source>${project.basedir}/carrello</source>
                <source>${project.basedir}/reportadeguatezza</source>
                <source>${project.basedir}/jsonsrv</source>
                <source>${project.basedir}/mifid</source>
                <source>${project.basedir}/copernicoprocess</source>
                <source>${project.basedir}/dataentryutil</source>
                <source>${project.basedir}/catalog</source>
                <source>${project.basedir}/sendprocess</source>
                <source>${project.basedir}/signprocess</source>
                <source>${project.basedir}/dataloader</source>
                <source>${project.basedir}/publisher</source>
                <source>${project.basedir}/idd</source>
			    <source>${project.basedir}/sostituzioni</source>
			    <source>${project.basedir}/messagecodesupdater</source>
			    <source>${project.basedir}/aml</source>
              </sources>
            </configuration>
          </execution>
			<execution>
				<id>add-test-source</id>
				<phase>generate-test-sources</phase>
				<goals>
					<goal>add-test-source</goal>
				</goals>
				<configuration>
					<sources>
						<source>${project.basedir}/test</source>
					</sources>
				</configuration>
			</execution>
        </executions>
      </plugin>
      <plugin>
        <artifactId>maven-antrun-plugin</artifactId>
        <executions>
          <execution>
            <phase>prepare-package</phase>
          </execution>
        </executions>
      </plugin>
	  <plugin>
		<groupId>org.jacoco</groupId>
		<artifactId>jacoco-maven-plugin</artifactId>
	  </plugin>
	  <plugin>
		<groupId>org.codehaus.mojo</groupId>
		<artifactId>truezip-maven-plugin</artifactId>
	   </plugin>
    </plugins>
  </build>
  <profiles>
    <profile>
      <id>copyjar</id>
      <build>
        <plugins>
          <plugin>
            <artifactId>maven-antrun-plugin</artifactId>
          </plugin>
        </plugins>
      </build>
    </profile>
  </profiles>
</project>
