use CEPE
go

delete from INR_CE_DOMINIO where DOMINIO_C_TABELLA = 'COPERNICO_SMART_NO_MILESTONE'
go
delete from INR_CE_DOMINIO where DOMINIO_C_TABELLA = 'COPERNICO_NO_MILESTONE_IF_POSTCOMPL'
go
delete from INR_CE_DOMINIO where DOMINIO_C_TABELLA = 'COPERNICO_NO_MILESTONE'
go

INSERT INTO INR_CE_DOMINIO (DOMINIO_C_TABELLA, DOMINIO_C_CODICE, DOMINIO_X_DESCR, DOMINIO_F_VALIDITA, DOMINIO_C_UTENTE)
VALUES ('COPERNICO_NO_MILESTONE_IF_POSTCOMPL', 'MOM_CODES_FONDI_IRL', 'FE02,FE03,FE23,FE05,FE15', 'S', NULL)
GO

INSERT INTO INR_CE_DOMINIO (DOMINIO_C_TABELLA, DOMINIO_C_CODICE, DOMINIO_X_DESCR, DOMINIO_F_VALIDITA, DOMINIO_C_UTENTE)
VALUES ('COPERNICO_NO_MILESTONE_IF_POSTCOMPL', 'MOM_CODES_FONDI_ITA', 'FI02,FI07,FI13', 'S', NULL)
GO

INSERT INTO INR_CE_DOMINIO (DOMINIO_C_TABELLA, DOMINIO_C_CODICE, DOMINIO_X_DESCR, DOMINIO_F_VALIDITA, DOMINIO_C_UTENTE)
VALUES ('COPERNICO_NO_MILESTONE', 'MOM_CODES_FDT1', 'FT38,FT24,FT37,FT39,FT01,FT02,FT27,FT05,FT06,FT08,FT07,FT25,FT36,FT09,FT10,FT11,FT42,FT21,FT13,FT20,FT26,FT29,FT31,FT17,FT33,FT23', 'S', NULL)
GO

INSERT INTO INR_CE_DOMINIO (DOMINIO_C_TABELLA, DOMINIO_C_CODICE, DOMINIO_X_DESCR, DOMINIO_F_VALIDITA, DOMINIO_C_UTENTE)
VALUES ('COPERNICO_NO_MILESTONE', 'MOM_CODES_FDT2', 'FT32,FT04,FT03,FT34,FT35,FL01,FT12,FT15,FT14,FT19', 'S', NULL)
GO

print 'Prodotti no milestone configurati'
go