<?xml version="1.0" encoding="ISO-8859-15"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>prgm.itap.dac</groupId>
    <artifactId>rdv-fe-wfem-itapdac</artifactId>
	<version>9.0.0</version>
  </parent>
  <artifactId>rdv-fe-wfem-itapdac-web</artifactId>
  <packaging>war</packaging>
  <name>ItaPDacWEB</name>
  <properties>
    <m2eclipse.wtp.contextRoot>ItaPDac</m2eclipse.wtp.contextRoot>
  </properties>
  <dependencies>
    <dependency>
      <groupId>com.atosorigin.wfem</groupId>
      <artifactId>rdv-be-wfem-framework-ejbimpl</artifactId>
      <version>${dep.rdv-be-wfem-framework-ejbimpl.version}</version>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>prgm.itap.dac</groupId>
      <artifactId>rdv-fe-wfem-itapdac-ejbimpl</artifactId>
      <version>${project.parent.version}</version>
      <scope>provided</scope>
    </dependency>
  </dependencies>
</project>
