package prgm.cedacri.adeguatezza.model;

import com.atosorigin.wfem.command.CommandDataModel;
import com.atosorigin.wfem.types.StringType;
import prgm.cedacri.adeguatezza.base.*;

public class OutputCtrlAdeguatezzaConvert implements ToModelConversion, ToBeanConversion 
{
	public Object convertToBean(CommandDataModel model) {
		OutputCtrlAdeguatezzaBean bean = new OutputCtrlAdeguatezzaBean();
		OutputCtrlAdeguatezzaModel internalModel = (OutputCtrlAdeguatezzaModel)model;
		bean.setDescErr (internalModel.getDescErr().getStringValue());
		bean.setEsito   (internalModel.getEsito().getStringValue());

		bean.setAdeNote1(internalModel.getAdeNote1().getStringValue());
		bean.setErrProf1(internalModel.getErrProf1().getStringValue());
		bean.setAdeTogg1(internalModel.getAdeTogg1().getStringValue());
		bean.setDesTogg1(internalModel.getDesTogg1().getStringValue());
		bean.setAdeDime1(internalModel.getAdeDime1().getStringValue());
		bean.setDesDime1(internalModel.getDesDime1().getStringValue());
		bean.setAdeFreq1(internalModel.getAdeFreq1().getStringValue());
		bean.setDesFreq1(internalModel.getDesFreq1().getStringValue());
		bean.setAdeObbi1(internalModel.getAdeObbi1().getStringValue());
		bean.setDesObbi1(internalModel.getDesObbi1().getStringValue());
		bean.setAdeOrit1(internalModel.getAdeOrit1().getStringValue());
		bean.setDesOrit1(internalModel.getDesOrit1().getStringValue());
		bean.setAdeModv1(internalModel.getAdeModv1().getStringValue());
		bean.setDesModv1(internalModel.getDesModv1().getStringValue());
		bean.setAdeNote2(internalModel.getAdeNote2().getStringValue());
		bean.setErrProf2(internalModel.getErrProf2().getStringValue());
		bean.setAdeTogg2(internalModel.getAdeTogg2().getStringValue());
		bean.setDesTogg2(internalModel.getDesTogg2().getStringValue());
		bean.setAdeDime2(internalModel.getAdeDime2().getStringValue());
		bean.setDesDime2(internalModel.getDesDime2().getStringValue());
		bean.setAdeFreq2(internalModel.getAdeFreq2().getStringValue());
		bean.setDesFreq2(internalModel.getDesFreq2().getStringValue());
		bean.setAdeObbi2(internalModel.getAdeObbi2().getStringValue());
		bean.setDesObbi2(internalModel.getDesObbi2().getStringValue());
		bean.setAdeOrit2(internalModel.getAdeOrit2().getStringValue());
		bean.setDesOrit2(internalModel.getDesOrit2().getStringValue());
		bean.setAdeModv2(internalModel.getAdeModv2().getStringValue());
		bean.setDesModv2(internalModel.getDesModv2().getStringValue());
		bean.setAdeNote3(internalModel.getAdeNote3().getStringValue());
		bean.setErrProf3(internalModel.getErrProf3().getStringValue());
		bean.setAdeTogg3(internalModel.getAdeTogg3().getStringValue());
		bean.setDesTogg3(internalModel.getDesTogg3().getStringValue());
		bean.setAdeDime3(internalModel.getAdeDime3().getStringValue());
		bean.setDesDime3(internalModel.getDesDime3().getStringValue());
		bean.setAdeFreq3(internalModel.getAdeFreq3().getStringValue());
		bean.setDesFreq3(internalModel.getDesFreq3().getStringValue());
		bean.setAdeObbi3(internalModel.getAdeObbi3().getStringValue());
		bean.setDesObbi3(internalModel.getDesObbi3().getStringValue());
		bean.setAdeOrit3(internalModel.getAdeOrit3().getStringValue());
		bean.setDesOrit3(internalModel.getDesOrit3().getStringValue());
		bean.setAdeModv3(internalModel.getAdeModv3().getStringValue());
		bean.setDesModv3(internalModel.getDesModv3().getStringValue());
		bean.setAdeNote4(internalModel.getAdeNote4().getStringValue());
		bean.setErrProf4(internalModel.getErrProf4().getStringValue());
		bean.setAdeTogg4(internalModel.getAdeTogg4().getStringValue());
		bean.setDesTogg4(internalModel.getDesTogg4().getStringValue());
		bean.setAdeDime4(internalModel.getAdeDime4().getStringValue());
		bean.setDesDime4(internalModel.getDesDime4().getStringValue());
		bean.setAdeFreq4(internalModel.getAdeFreq4().getStringValue());
		bean.setDesFreq4(internalModel.getDesFreq4().getStringValue());
		bean.setAdeObbi4(internalModel.getAdeObbi4().getStringValue());
		bean.setDesObbi4(internalModel.getDesObbi4().getStringValue());
		bean.setAdeOrit4(internalModel.getAdeOrit4().getStringValue());
		bean.setDesOrit4(internalModel.getDesOrit4().getStringValue());
		bean.setAdeModv4(internalModel.getAdeModv4().getStringValue());
		bean.setDesModv4(internalModel.getDesModv4().getStringValue());
		bean.setAdeDisi1(internalModel.getAdeDisi1().getStringValue());
		bean.setAdeDisi2(internalModel.getAdeDisi2().getStringValue());
		bean.setAdeDisi3(internalModel.getAdeDisi3().getStringValue());
		bean.setAdeDisi4(internalModel.getAdeDisi4().getStringValue());
		bean.setDesDisi1(internalModel.getDesDisi1().getStringValue());
		bean.setDesDisi2(internalModel.getDesDisi2().getStringValue());
		bean.setDesDisi3(internalModel.getDesDisi3().getStringValue());
		bean.setDesDisi4(internalModel.getDesDisi4().getStringValue());
		bean.setAdeAttCo(internalModel.getAdeAttCo().getStringValue());
		bean.setAdeTitCo(internalModel.getAdeTitCo().getStringValue());
		return bean;
	}

	public CommandDataModel convertToModel(Object bean) {
		OutputCtrlAdeguatezzaBean internalBean = (OutputCtrlAdeguatezzaBean)bean;
		OutputCtrlAdeguatezzaModel model = new OutputCtrlAdeguatezzaModel();
		model.setDescErr (new StringType(internalBean.getDescErr()));
		model.setEsito   (new StringType(internalBean.getEsito()));

		model.setAdeNote1(new StringType(internalBean.getAdeNote1()));
		model.setErrProf1(new StringType(internalBean.getErrProf1()));
		model.setAdeTogg1(new StringType(internalBean.getAdeTogg1()));
		model.setDesTogg1(new StringType(internalBean.getDesTogg1()));
		model.setAdeDime1(new StringType(internalBean.getAdeDime1()));
		model.setDesDime1(new StringType(internalBean.getDesDime1()));
		model.setAdeFreq1(new StringType(internalBean.getAdeFreq1()));
		model.setDesFreq1(new StringType(internalBean.getDesFreq1()));
		model.setAdeObbi1(new StringType(internalBean.getAdeObbi1()));
		model.setDesObbi1(new StringType(internalBean.getDesObbi1()));
		model.setAdeOrit1(new StringType(internalBean.getAdeOrit1()));
		model.setDesOrit1(new StringType(internalBean.getDesOrit1()));
		model.setAdeModv1(new StringType(internalBean.getAdeModv1()));
		model.setDesModv1(new StringType(internalBean.getDesModv1()));
		model.setAdeNote2(new StringType(internalBean.getAdeNote2()));
		model.setErrProf2(new StringType(internalBean.getErrProf2()));
		model.setAdeTogg2(new StringType(internalBean.getAdeTogg2()));
		model.setDesTogg2(new StringType(internalBean.getDesTogg2()));
		model.setAdeDime2(new StringType(internalBean.getAdeDime2()));
		model.setDesDime2(new StringType(internalBean.getDesDime2()));
		model.setAdeFreq2(new StringType(internalBean.getAdeFreq2()));
		model.setDesFreq2(new StringType(internalBean.getDesFreq2()));
		model.setAdeObbi2(new StringType(internalBean.getAdeObbi2()));
		model.setDesObbi2(new StringType(internalBean.getDesObbi2()));
		model.setAdeOrit2(new StringType(internalBean.getAdeOrit2()));
		model.setDesOrit2(new StringType(internalBean.getDesOrit2()));
		model.setAdeModv2(new StringType(internalBean.getAdeModv2()));
		model.setDesModv2(new StringType(internalBean.getDesModv2()));
		model.setAdeNote3(new StringType(internalBean.getAdeNote3()));
		model.setErrProf3(new StringType(internalBean.getErrProf3()));
		model.setAdeTogg3(new StringType(internalBean.getAdeTogg3()));
		model.setDesTogg3(new StringType(internalBean.getDesTogg3()));
		model.setAdeDime3(new StringType(internalBean.getAdeDime3()));
		model.setDesDime3(new StringType(internalBean.getDesDime3()));
		model.setAdeFreq3(new StringType(internalBean.getAdeFreq3()));
		model.setDesFreq3(new StringType(internalBean.getDesFreq3()));
		model.setAdeObbi3(new StringType(internalBean.getAdeObbi3()));
		model.setDesObbi3(new StringType(internalBean.getDesObbi3()));
		model.setAdeOrit3(new StringType(internalBean.getAdeOrit3()));
		model.setDesOrit3(new StringType(internalBean.getDesOrit3()));
		model.setAdeModv3(new StringType(internalBean.getAdeModv3()));
		model.setDesModv3(new StringType(internalBean.getDesModv3()));
		model.setAdeNote4(new StringType(internalBean.getAdeNote4()));
		model.setErrProf4(new StringType(internalBean.getErrProf4()));
		model.setAdeTogg4(new StringType(internalBean.getAdeTogg4()));
		model.setDesTogg4(new StringType(internalBean.getDesTogg4()));
		model.setAdeDime4(new StringType(internalBean.getAdeDime4()));
		model.setDesDime4(new StringType(internalBean.getDesDime4()));
		model.setAdeFreq4(new StringType(internalBean.getAdeFreq4()));
		model.setDesFreq4(new StringType(internalBean.getDesFreq4()));
		model.setAdeObbi4(new StringType(internalBean.getAdeObbi4()));
		model.setDesObbi4(new StringType(internalBean.getDesObbi4()));
		model.setAdeOrit4(new StringType(internalBean.getAdeOrit4()));
		model.setDesOrit4(new StringType(internalBean.getDesOrit4()));
		model.setAdeModv4(new StringType(internalBean.getAdeModv4()));
		model.setDesModv4(new StringType(internalBean.getDesModv4()));
		model.setAdeDisi1(new StringType(internalBean.getAdeDisi1()));
		model.setAdeDisi2(new StringType(internalBean.getAdeDisi2()));
		model.setAdeDisi3(new StringType(internalBean.getAdeDisi3()));
		model.setAdeDisi4(new StringType(internalBean.getAdeDisi4()));
		model.setDesDisi1(new StringType(internalBean.getDesDisi1()));
		model.setDesDisi2(new StringType(internalBean.getDesDisi2()));
		model.setDesDisi3(new StringType(internalBean.getDesDisi3()));
		model.setDesDisi4(new StringType(internalBean.getDesDisi4()));
		model.setAdeAttCo(new StringType(internalBean.getAdeAttCo()));
		model.setAdeTitCo(new StringType(internalBean.getAdeTitCo()));
		
		return (CommandDataModel)model;
	}
}
