use CEPE
go

delete from PDF_AREAS where AREA = 'CATALOGO_OPERAZIONI'
go
insert into PDF_AREAS (AREA, DESCR) values ('CATALOGO_OPERAZIONI', 'Catalogo operazioni')
go

delete from INR_CE_DOMINIO where DOMINIO_C_TABELLA = 'PDFWEBFORMS_CONFIG_PARAMS' and DOMINIO_C_CODICE = 'AREE_CRAFTER'
go
insert into INR_CE_DOMINIO (DOMINIO_C_TABELLA, DOMINIO_C_CODICE, DOMINIO_X_DESCR, DOMINIO_F_VALIDITA)
values ('PDFWEBFORMS_CONFIG_PARAMS', 'AREE_CRAFTER', 'CATALOGO_MODULI,CATALOGO_OPERAZIONI', 'S')
go

PRINT "Area aggiunta"

