use CEPE
go

delete from INR_CE_DOMINIO where DOMINIO_C_TABELLA = 'PILOTA_COPERNICO_SMART'
and DOMINIO_C_CODICE like ('PRODOTTI_%_MYLIFE')
go

insert into INR_CE_DOMINIO (DOMINIO_C_TABELLA, DOMINIO_C_CODICE, DOMINIO_X_DESCR, DOMINIO_F_VALIDITA)
values ('PILOTA_COPERNICO_SMART', 'PRODOTTI_SOLO_FULL_MYLIFE', 'IA45,IA74,IA78,IA95', 'S')
go

insert into INR_CE_DOMINIO (DOMINIO_C_TABELLA, DOMINIO_C_CODICE, DOMINIO_X_DESCR, DOMINIO_F_VALIDITA)
values ('PILOTA_COPERNICO_SMART', 'PRODOTTI_ANCHE_FULL_MYLIFE', 'IA41,IA73,IA77,IA92', 'S')
go

insert into INR_CE_DOMINIO (DOMINIO_C_TABELLA, DOMINIO_C_CODICE, DOMINIO_X_DESCR, DOMINIO_F_VALIDITA)
values ('PILOTA_COPERNICO_SMART', 'PRODOTTI_SOLO_SMART_MYLIFE', 'IA38,IA71,IA72,IA88', 'S')
go

