use CEPE
go

delete from INR_CE_DOMINIO where DOMINIO_C_TABELLA = 'PILOTA_COPERNICO_SMART'
and DOMINIO_C_CODICE like ('PRODOTTI_%_FONDIPIR')
go

insert into INR_CE_DOMINIO (DOMINIO_C_TABELLA, DOMINIO_C_CODICE, DOMINIO_X_DESCR, DOMINIO_F_VALIDITA)
values ('PILOTA_COPERNICO_SMART', 'PRODOTTI_ANCHE_FULL_FONDIPIR', 'FI11,FI12', 'S')
go

