use CEPE
go

delete from INR_CE_DOMINIO where DOMINIO_C_TABELLA = 'PILOTA_COPERNICO_SMART'
and DOMINIO_C_CODICE like ('PRODOTTI_%_PERSONALPIR')
go

insert into INR_CE_DOMINIO (DOMINIO_C_TABELLA, DOMINIO_C_CODICE, DOMINIO_X_DESCR, DOMINIO_F_VALIDITA)
values ('PILOTA_COPERNICO_SMART', 'PRODOTTI_SOLO_SMART_PERSONALPIR', 'IA99,IAA1,IAA2,IAA3', 'S')
go

