use CEPE
go

delete from INR_CE_DOMINIO where DOMINIO_C_TABELLA = 'PILOTA_COPERNICO_SMART'
and DOMINIO_C_CODICE not like ('CLIENTI_IN_PILOTA%')
go

INSERT INTO INR_CE_DOMINIO (DOMINIO_C_TABELLA, DOMINIO_C_CODICE, DOMINIO_X_DESCR, DOMINIO_F_VALIDITA, DOMINIO_C_UTENTE)
VALUES ('PILOTA_COPERNICO_SMART', 'PRODOTTI_SOLO_FULL_FONDI_IRL', 'FE02,FE03,FE05,FE15,FE23', 'S', NULL)
GO
INSERT INTO INR_CE_DOMINIO (DOMINIO_C_TABELLA, DOMINIO_C_CODICE, DOMINIO_X_DESCR, DOMINIO_F_VALIDITA, DOMINIO_C_UTENTE)
VALUES ('PILOTA_COPERNICO_SMART', 'PRODOTTI_SOLO_FULL_FONDI_ITA', 'FI02,FI07,FI13', 'S', NULL)
GO
INSERT INTO INR_CE_DOMINIO (DOMINIO_C_TABELLA, DOMINIO_C_CODICE, DOMINIO_X_DESCR, DOMINIO_F_VALIDITA, DOMINIO_C_UTENTE)
VALUES ('PILOTA_COPERNICO_SMART', 'PRODOTTI_SOLO_FULL_FDT1', 'FT38,FT24,FT37,FT39,FT01,FT02,FT27,FT05,FT06,FT08,FT07,FT25,FT36,FT09,FT10,FT11,FT42,FT21,FT13,FT20,FT26,FT29,FT31,FT17,FT33,FT23', 'S', NULL)
GO
INSERT INTO INR_CE_DOMINIO (DOMINIO_C_TABELLA, DOMINIO_C_CODICE, DOMINIO_X_DESCR, DOMINIO_F_VALIDITA, DOMINIO_C_UTENTE)
VALUES ('PILOTA_COPERNICO_SMART', 'PRODOTTI_SOLO_FULL_FDT2', 'FT32,FT04,FT03,FT34,FT35,FL01,FT12,FT15,FT14,FT19', 'S', NULL)
GO

INSERT INTO INR_CE_DOMINIO (DOMINIO_C_TABELLA, DOMINIO_C_CODICE, DOMINIO_X_DESCR, DOMINIO_F_VALIDITA, DOMINIO_C_UTENTE)
VALUES ('PILOTA_COPERNICO_SMART', 'PRODOTTI_ANCHE_FULL_FONDIPIR', 'FI11,FI12', 'S', NULL)
GO
INSERT INTO INR_CE_DOMINIO (DOMINIO_C_TABELLA, DOMINIO_C_CODICE, DOMINIO_X_DESCR, DOMINIO_F_VALIDITA, DOMINIO_C_UTENTE)
VALUES ('PILOTA_COPERNICO_SMART', 'PRODOTTI_ANCHE_FULL_GPM', 'GP07,GP08,GP09', 'S', NULL)
GO
INSERT INTO INR_CE_DOMINIO (DOMINIO_C_TABELLA, DOMINIO_C_CODICE, DOMINIO_X_DESCR, DOMINIO_F_VALIDITA, DOMINIO_C_UTENTE)
VALUES ('PILOTA_COPERNICO_SMART', 'PRODOTTI_ANCHE_FULL_MYLIFE', 'IA41,IA73,IA77,IA92,IA45,IA74,IA78,IA95', 'S', NULL)
GO


INSERT INTO INR_CE_DOMINIO (DOMINIO_C_TABELLA, DOMINIO_C_CODICE, DOMINIO_X_DESCR, DOMINIO_F_VALIDITA, DOMINIO_C_UTENTE)
VALUES ('PILOTA_COPERNICO_SMART', 'PRODOTTI_SOLO_SMART_GPM', 'GP06', 'S', NULL)
GO
INSERT INTO INR_CE_DOMINIO (DOMINIO_C_TABELLA, DOMINIO_C_CODICE, DOMINIO_X_DESCR, DOMINIO_F_VALIDITA, DOMINIO_C_UTENTE)
VALUES ('PILOTA_COPERNICO_SMART', 'PRODOTTI_SOLO_SMART_MYLIFE', 'IA38,IA71,IA72,IA88,IA44,IA43,IA76,IA75,IA80,IA79,IA93,IA94', 'S', NULL)
GO
INSERT INTO INR_CE_DOMINIO (DOMINIO_C_TABELLA, DOMINIO_C_CODICE, DOMINIO_X_DESCR, DOMINIO_F_VALIDITA, DOMINIO_C_UTENTE)
VALUES ('PILOTA_COPERNICO_SMART', 'PRODOTTI_SOLO_SMART_PERSONALPIR', 'IA99,IAA1,IAA2,IAA3', 'S', NULL)
GO

