use CEPE
go

delete from INR_CE_DOMINIO where DOMINIO_C_TABELLA = 'PILOTA_COPERNICO_SMART'
and DOMINIO_C_CODICE = 'CLIENTI_IN_PILOTA'
go

insert into INR_CE_DOMINIO (DOMINIO_C_TABELLA, DOMINIO_C_CODICE, DOMINIO_X_DESCR, DOMINIO_F_VALIDITA)
values ('PILOTA_COPERNICO_SMART', 'CLIENTI_IN_PILOTA', '00000000000', 'S')
go