use CEPE
go

update PDF_ANAG set	HAS_CONTROLLO_AML_PEP=null
go

update PDF_ANAG set	HAS_CONTROLLO_AML_PEP='S'	where MOM_CODE=	'IA18'
update PDF_ANAG set	HAS_CONTROLLO_AML_PEP='S'	where MOM_CODE=	'FE23'
update PDF_ANAG set	HAS_CONTROLLO_AML_PEP='S'	where MOM_CODE=	'FE03'
update PDF_ANAG set	HAS_CONTROLLO_AML_PEP='S'	where MOM_CODE=	'FE02'
update PDF_ANAG set	HAS_CONTROLLO_AML_PEP='S'	where MOM_CODE=	'FI07'
update PDF_ANAG set	HAS_CONTROLLO_AML_PEP='S'	where MOM_CODE=	'FI02'
update PDF_ANAG set	HAS_CONTROLLO_AML_PEP='S'	where MOM_CODE=	'FT29'
update PDF_ANAG set	HAS_CONTROLLO_AML_PEP='S'	where MOM_CODE=	'FT31'
update PDF_ANAG set	HAS_CONTROLLO_AML_PEP='S'	where DRIVER_NAME='fonditerziiniziale'
update PDF_ANAG set	HAS_CONTROLLO_AML_PEP='S'	where MOM_CODE=	'IAC7'
update PDF_ANAG set	HAS_CONTROLLO_AML_PEP='S'	where MOM_CODE=	'IA16'
update PDF_ANAG set	HAS_CONTROLLO_AML_PEP='S'	where MOM_CODE=	'IAF5'
update PDF_ANAG set	HAS_CONTROLLO_AML_PEP='S'	where MOM_CODE=	'IAF8'
update PDF_ANAG set	HAS_CONTROLLO_AML_PEP='S'	where DRIVER_NAME='mediolanumpiu'
update PDF_ANAG set	HAS_CONTROLLO_AML_PEP='S'	where MOM_CODE=	'IA41'
update PDF_ANAG set	HAS_CONTROLLO_AML_PEP='S'	where MOM_CODE=	'IA38'
update PDF_ANAG set	HAS_CONTROLLO_AML_PEP='S'	where MOM_CODE=	'IA92'
update PDF_ANAG set	HAS_CONTROLLO_AML_PEP='S'	where MOM_CODE=	'IA88'
update PDF_ANAG set	HAS_CONTROLLO_AML_PEP='S'	where MOM_CODE=	'IA73'
update PDF_ANAG set	HAS_CONTROLLO_AML_PEP='S'	where MOM_CODE=	'IA71'
update PDF_ANAG set	HAS_CONTROLLO_AML_PEP='S'	where MOM_CODE=	'IA77'
update PDF_ANAG set	HAS_CONTROLLO_AML_PEP='S'	where MOM_CODE=	'IA72'
update PDF_ANAG set	HAS_CONTROLLO_AML_PEP='S'	where MOM_CODE=	'IA26'
update PDF_ANAG set	HAS_CONTROLLO_AML_PEP='S'	where MOM_CODE=	'IAA1'
update PDF_ANAG set	HAS_CONTROLLO_AML_PEP='S'	where MOM_CODE=	'IA99'
update PDF_ANAG set	HAS_CONTROLLO_AML_PEP='S'	where MOM_CODE=	'IAC4'
update PDF_ANAG set	HAS_CONTROLLO_AML_PEP='S'	where MOM_CODE=	'IA35'
go

PRINT 'Flag controllo PEP aggiornati'
go

