<?xml version="1.0" encoding="ISO-8859-15"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.atosorigin.wfem</groupId>
  <artifactId>rdv-lib-wfem-thirdparty</artifactId>
  <version>3.0.0</version>
  <packaging>pom</packaging>
  <name>rdv-lib-wfem-thirdparty</name>
  <modules>
    <module>rdv-lib-wfem-thirdparty-deps</module>
    <module>rdv-lib-wfem-thirdparty-ear</module>
  </modules>
  <properties>
    <dep.ant.version>1.7.0</dep.ant.version>
    <dep.castor.version>1.2</dep.castor.version>
    <dep.commons-beanutils.version>1.9.3</dep.commons-beanutils.version>
    <dep.commons-codec.version>1.16.1</dep.commons-codec.version>
    <dep.commons-collections.version>3.2.2</dep.commons-collections.version>
    <dep.commons-fileupload.version>1.3.3</dep.commons-fileupload.version>
    <dep.commons-httpclient.version>3.1</dep.commons-httpclient.version>
    <dep.commons-jexl.version>1.1</dep.commons-jexl.version>
    <dep.commons-jexl2.version>2.1.1</dep.commons-jexl2.version>
    <dep.commons-lang.version>2.6</dep.commons-lang.version>
    <dep.commons-logging.version>1.2</dep.commons-logging.version>
    <dep.dom4j.version>1.6.1</dep.dom4j.version>
    <dep.ezmorph.version>1.0.6</dep.ezmorph.version>
    <dep.fontbox.version>3.0.3</dep.fontbox.version>
    <dep.itext.version>2.0.8</dep.itext.version>
    <dep.itextpdf.version>5.4.3</dep.itextpdf.version>
    <dep.jackson-annotations.version>2.9.5</dep.jackson-annotations.version>
    <dep.jackson-core.version>2.9.5</dep.jackson-core.version>
    <dep.jackson-databind.version>2.9.5</dep.jackson-databind.version>
    <dep.javaee-api.version>6.0</dep.javaee-api.version>
    <dep.jaxen.version>1.1.6</dep.jaxen.version>
    <dep.jcommon.version>1.0.24</dep.jcommon.version>
    <dep.jdom.version>1.1.3</dep.jdom.version>
    <dep.jfreechart.version>1.0.19</dep.jfreechart.version>
    <dep.json-lib.version>2.4</dep.json-lib.version>
    <dep.junit.version>4.12</dep.junit.version>
    <dep.log4j.version>1.2.17</dep.log4j.version>
    <dep.mock-jaguar-jcm.version>1.0.0</dep.mock-jaguar-jcm.version>      
    <dep.nekohtml.version>1.9.7</dep.nekohtml.version>
    <dep.ojdbc14.version>1.0</dep.ojdbc14.version>
    <dep.pdfbox.version>3.0.3</dep.pdfbox.version>
    <dep.poi.version>3.13</dep.poi.version>
    <dep.spring.version>2.5.6.SEC03</dep.spring.version>
    <dep.sybase-client.version>1.0.0</dep.sybase-client.version>
    <dep.xercesimpl.version>2.9.1</dep.xercesimpl.version>
    <dep.esapi.version>2.2.0.0</dep.esapi.version>
    <dep.spring.version>2.5.4</dep.spring.version>
    
	<!-- Nuove variabili aggiunte -->
	<dep.pdfbox-tools.version>3.0.3</dep.pdfbox-tools.version>
	<dep.pdfbox-debugger.version>3.0.3</dep.pdfbox-debugger.version>
	<dep.preflight.version>3.0.3</dep.preflight.version>
	<dep.xmpbox.version>3.0.3</dep.xmpbox.version>
	<dep.commons-csv.version>1.11.0</dep.commons-csv.version>
	<dep.commons-cli.version>1.8.0</dep.commons-cli.version>
	<dep.kotlin-stdlib.version>1.6.0</dep.kotlin-stdlib.version>
	<dep.kotlin-stdlib-common.version>1.6.21</dep.kotlin-stdlib-common.version>
	<dep.kotlin-reflect.version>1.6.0</dep.kotlin-reflect.version>
	<dep.slf4j.version>1.7.36</dep.slf4j.version>
	<dep.jaxb-api.version>2.3.0</dep.jaxb-api.version>
	<dep.jaxb-core.version>2.3.0</dep.jaxb-core.version>
	<dep.jaxb-impl.version>2.3.0</dep.jaxb-impl.version>
	<dep.jakarta-xml-bind-api.version>3.0.1</dep.jakarta-xml-bind-api.version>
	<dep.jakarta-activation-api.version>2.0.1</dep.jakarta-activation-api.version>

    <dep.fastutil.version>8.5.8</dep.fastutil.version>
    <dep.jempbox.version>1.8.17</dep.jempbox.version>
    <dep.jts-core.version>1.20.0</dep.jts-core.version>
    <dep.moshi.version>1.13.0</dep.moshi.version>
    <dep.moshi-kotlin.version>1.13.0</dep.moshi-kotlin.version>
    <dep.okio.version>2.10.0</dep.okio.version>
    <dep.logback.version>1.2.13</dep.logback.version>
    
    <plugin.build-helper-maven-plugin.version>3.0.0</plugin.build-helper-maven-plugin.version>
    <plugin.lifecycle-mapping.version>1.0.0</plugin.lifecycle-mapping.version>
    <plugin.maven-ear-plugin.version>2.10</plugin.maven-ear-plugin.version>
    <plugin.sortpom-maven-plugin.version>2.4.0</plugin.sortpom-maven-plugin.version>
    <plugin.weblogic-maven-plugin.adminurl>t3://localhost:7001</plugin.weblogic-maven-plugin.adminurl>
    <plugin.weblogic-maven-plugin.password>welcome1</plugin.weblogic-maven-plugin.password>
    <plugin.weblogic-maven-plugin.targets>AdminServer</plugin.weblogic-maven-plugin.targets>
    <plugin.weblogic-maven-plugin.user>weblogic</plugin.weblogic-maven-plugin.user>
    <plugin.weblogic-maven-plugin.version>10.3.6.0</plugin.weblogic-maven-plugin.version>
    <project.build.sourceEncoding>ISO-8859-15</project.build.sourceEncoding>
    <project.build.sourceJdk>1.6</project.build.sourceJdk>
    <project.build.targetEncoding>ISO-8859-15</project.build.targetEncoding>
    <project.build.targetJdk>1.6</project.build.targetJdk>
  </properties>

  <build>
    <directory>${project.basedir}/bin</directory>
    <resources>
      <resource>
        <filtering>true</filtering>
        <directory>src/main/resources</directory>
      </resource>
      <resource>
        <filtering>true</filtering>
        <directory>src/main/application</directory>
      </resource>
    </resources>

    <pluginManagement>
      <plugins>
        <plugin>
          <groupId>com.oracle.weblogic</groupId>
          <artifactId>weblogic-maven-plugin</artifactId>
          <version>${plugin.weblogic-maven-plugin.version}</version>
          <configuration>
            <adminurl>${plugin.weblogic-maven-plugin.adminurl}</adminurl>
            <user>${plugin.weblogic-maven-plugin.user}</user>
            <password>${plugin.weblogic-maven-plugin.password}</password>
            <targets>${plugin.weblogic-maven-plugin.targets}</targets>
            <source>${project.build.directory}/${project.build.finalName}.${project.packaging}</source>
            <name>${project.build.finalName}</name>
            <isLibrary>true</isLibrary>
            <action>deploy</action>
            <verbose>true</verbose>
          </configuration>
          <executions>
            <execution>
              <goals>
                <goal>deploy</goal>
              </goals>
              <phase>install</phase>
            </execution>
          </executions>
        </plugin>       
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-ear-plugin</artifactId>
          <version>${plugin.maven-ear-plugin.version}</version>
        </plugin>
        <plugin>
          <groupId>org.codehaus.mojo</groupId>
          <artifactId>build-helper-maven-plugin</artifactId>
          <version>${plugin.build-helper-maven-plugin.version}</version>
          <executions>
            <execution>
              <id>parse-version</id>
              <goals>
                <goal>parse-version</goal>
              </goals>
              <phase>validate</phase>
            </execution>
          </executions>
        </plugin>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-ear-plugin</artifactId>
          <configuration>
            <filtering>true</filtering>
            <version>5</version>
            <defaultLibBundleDir>lib</defaultLibBundleDir>
            <displayName>${project.parent.name}</displayName>
            <archive>
              <addMavenDescriptor>true</addMavenDescriptor>
              <manifest>
                <addDefaultImplementationEntries>false</addDefaultImplementationEntries>
                <addDefaultSpecificationEntries>false</addDefaultSpecificationEntries>
              </manifest>
              <manifestEntries>
                <Created-On>${build.timestamp}</Created-On>
                <extension-name>${project.parent.name}</extension-name>
                <specification-title>${project.parent.name}-${project.version}</specification-title>
                <specification-version>${parsedVersion.majorVersion}.${parsedVersion.minorVersion}.${parsedVersion.incrementalVersion}</specification-version>
                <implementation-version>${parsedVersion.majorVersion}.${parsedVersion.minorVersion}.${parsedVersion.incrementalVersion}</implementation-version>
                <implementation-vendor>Engineering</implementation-vendor>
              </manifestEntries>
            </archive>
          </configuration>
        </plugin>
      </plugins>
    </pluginManagement>
    <plugins>
      <plugin>
        <groupId>org.codehaus.mojo</groupId>
        <artifactId>build-helper-maven-plugin</artifactId>
      </plugin>
    </plugins>
  </build>
</project>
