<?xml version="1.0" encoding="ISO-8859-15"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>prgm.itap.dac</groupId>
    <artifactId>rdv-fe-wfem-itapdac</artifactId>
	<version>9.0.0</version>
  </parent>
  <artifactId>rdv-fe-wfem-itapdac-ear</artifactId>
  <packaging>ear</packaging>
  <name>ItaPDacEAR</name>
  <dependencies>
    <dependency>
      <groupId>${project.parent.groupId}</groupId>
      <artifactId>${project.parent.artifactId}-ejbimpl</artifactId>
      <version>${project.parent.version}</version>
      <type>ejb</type>
    </dependency>
    <dependency>
      <groupId>${project.parent.groupId}</groupId>
      <artifactId>${project.parent.artifactId}-web</artifactId>
      <version>${project.parent.version}</version>
      <type>war</type>
    </dependency>
  </dependencies>
  <build>
    <resources>
      <resource>
        <filtering>true</filtering>
        <directory>src/main/application/META-INF</directory>
      </resource>
    </resources>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-ear-plugin</artifactId>
        <configuration>
          <modules>
            <ejbModule>
              <groupId>${project.parent.groupId}</groupId>
              <artifactId>${project.parent.artifactId}-ejbimpl</artifactId>
              <bundleFileName>ItaPDac.jar</bundleFileName>
            </ejbModule>
            <webModule>
              <groupId>${project.parent.groupId}</groupId>
              <artifactId>${project.parent.artifactId}-web</artifactId>
              <bundleFileName>ItaPDacWEB.war</bundleFileName>
              <contextRoot>ItaPDac</contextRoot>
            </webModule>
             <jarModule>
               <groupId>org.jacoco</groupId>
               <artifactId>org.jacoco.agent</artifactId>                     
               <excluded>true</excluded>
            </jarModule>
          </modules>
        </configuration>
      </plugin>
    </plugins>
  </build>
  <profiles>
    <profile>
      <id>bea</id>
      <build>
        <plugins>
          <plugin>
            <groupId>com.oracle.weblogic</groupId>
            <artifactId>weblogic-maven-plugin</artifactId>
          </plugin>
        </plugins>
      </build>
    </profile>
  </profiles>
</project>
