<?xml version="1.0" encoding="ISO-8859-15"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>com.atosorigin.wfem</groupId>
    <artifactId>rdv-be-wfem-framework</artifactId>
    <version>22.0.0-RC-SNAPSHOT</version>
  </parent>
  <artifactId>rdv-be-wfem-framework-ear</artifactId>
  <packaging>ear</packaging>
  <name>WfemEAR</name>
  <dependencies>
    <dependency>
      <groupId>${project.parent.groupId}</groupId>
      <artifactId>${project.parent.artifactId}-ejbimpl</artifactId>
      <version>${project.parent.version}</version>
      <type>ejb</type>
    </dependency>
  </dependencies>
  <build>
    <resources>
      <resource>
        <filtering>true</filtering>
        <directory>src/main/application/META-INF</directory>
      </resource>
    </resources>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-ear-plugin</artifactId>
        <configuration>
          <modules>
            <ejbModule>
              <groupId>${project.parent.groupId}</groupId>
              <artifactId>${project.parent.artifactId}-ejbimpl</artifactId>
              <bundleFileName>Wfem.jar</bundleFileName>
            </ejbModule>
            <jarModule>
               <groupId>org.jacoco</groupId>
			   <artifactId>org.jacoco.agent</artifactId>				
               <excluded>true</excluded>
            </jarModule>
          </modules>
        </configuration>
      </plugin>
    </plugins>
  </build>
  <profiles>
    <profile>
      <id>bea</id>
      <build>
        <plugins>
          <plugin>
            <groupId>com.oracle.weblogic</groupId>
            <artifactId>weblogic-maven-plugin</artifactId>
          </plugin>
        </plugins>
      </build>
    </profile>
  </profiles>
</project>
